In [1]:
import pandas as pd
import numpy as np

In [2]:
#9.2.3
#Какие элементы расположены в последнем столбце массива, заданного с помощью кода выше?

my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [3]:
my_array = np.array([x for x in range(10)])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[5]

5

In [5]:
my_array[-1]

9

In [6]:
my_array[3:6]

array([3, 4, 5])

In [7]:
my_array[1:8:3]

array([1, 4, 7])

In [8]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [9]:
my_array[1][2]

12

In [10]:
my_array[1,2]

12

In [11]:
#Потренируемся извлекать из двумерного массива отдельные элементы и их срезы и производить над ними математические действия.
#Задания блока будем выполнять на примере массива, созданного кодом:

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [12]:
#9.3.1
#Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после точки-разделителя.

print("%.2f" % big_secret.sum(axis=0)[-1])

3154.33


In [13]:
#9.3.2
#Выделите из каждой строки массива big_secret первые 5 элементов. 
#Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после точки-разделителя.

b = big_secret[:, 0:5]
print("%.2f" % np.trace(b))

121.37


In [14]:
#9.3.3
#Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали
    #получившейся матрицы? Введите полученный результат без изменений и округлений, в качестве разделителя используйте точку.
    
b = big_secret[:, -5:]
print(b.diagonal().prod())

341505315559.2347


In [15]:
#Важное отличие массивов NumPy от списков Python — при изменении среза или отдельных элементов все изменения касаются
    #не только самого среза, но и падают в исходный массив, даже если перед внесением изменений срез был сохранён в
    #виде отдельной переменной. Изначально NumPy проектировался для работы с большими массивами данных, 
    #поэтому при бесконтрольном копировании фрагментов массивов возникли бы проблемы с быстродействием и памятью.

#Создадим массив 4х6
my_array = np.random.randint(1, 100, (4, 6)) 
my_array

array([[84, 53, 72, 84, 33, 81],
       [89, 94, 39, 69, 90, 42],
       [24, 74,  4, 12,  3, 89],
       [14,  5, 11, 21, 50, 39]])

In [16]:
#Массив создаётся с помощью генератора случайных чисел, при выполнении кода у вас могут получиться другие значения.
#Выделим из созданного массива квадрат 2 х 2, содержащий 4 элемента, расположенные в центре матрицы:
my_slice = my_array[1:3, 2:4]
my_slice

array([[39, 69],
       [ 4, 12]])

In [17]:
#Заменим эти элементы на нули и посмотрим, как изменится содержимое исходной матрицы:
my_slice[:] = 0
my_array

array([[84, 53, 72, 84, 33, 81],
       [89, 94,  0,  0, 90, 42],
       [24, 74,  0,  0,  3, 89],
       [14,  5, 11, 21, 50, 39]])

In [18]:
#Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные,
    #и на -1 все элементы, у которых оба индекса чётные.
big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret[1::1, 1::2] = 1
big_secret[0::2, 0::2] = -1

In [19]:
#9.3.4
#Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. 
    #Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.
    
b = big_secret[:, 0:5]
print(np.trace(b))

-1.0


In [20]:
#9.3.5
#Выделите из каждой строки обновлённого массива big_secret последние 5 элементов.
#Чему равно произведение элементов главной диагонали получившейся матрицы?
#Введите полученный результат без изменений и округлений.

b = big_secret[:, -5:]
print(b.diagonal().prod())

-1.0


In [21]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

#9.4.1
#Сколько столбцов содержит массив great_secret?
great_secret.shape

(100, 3)

In [22]:
#9.4.2
#Чему равна сумма косинусов элементов первой строки массива great_secret?
    #Ответ округлите до двух знаков после точки-разделителя:
print ("%.2f" % np.sum(np.cos(great_secret[0])))

0.16


In [23]:
#9.4.3
#Чему равна сумма элементов массива great_secret, значение которых больше 50?

np.sum(great_secret[great_secret>50])

5470.0

In [24]:
#9.4.4
#Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?
#Скопируйте ответ из Jupyter Notebook без изменений:

great_secret.flatten()[150]

7.0710678118654755

In [25]:
#9.4.5
#Отсортируйте значения столбцов массива great_secret по возрастанию.
#Чему равна сумма элементов последней строки отсортированного массива?
#Ответ округлите до двух цифр после точки-разделителя:

print ("%.2f" % np.sum(np.sort(great_secret, axis=0)[-1]))

115.12


In [26]:
students = np.array([[1, 135, 34, 4], [2, 160, 43, 5], [3, 163, 40, 4.3], [4, 147, 44, 5],
                    [5, 138, 41, 4.7], [6, 149, 54, 3.9], [7, 136, 39, 4.2], [8, 154, 48, 4.9], 
                    [9, 137, 35, 3.7], [10, 165, 60, 4.6]])
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [27]:
#9.5.1
#Чему равно медианное значение массы тела школьников?

median_weight = np.median(students[:, -2])
median_weight

42.0

In [28]:
#9.5.2
#На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя?
#Дайте ответ в килограммах с точностью до одной десятой кг, в качестве разделителя используйте точку.

avg_weight = np.mean(students[:, -2])
print(avg_weight)
print(avg_weight - median_weight)

43.8
1.7999999999999972


In [29]:
#9.5.3
#Из предложенных пар признаков в массиве students выберите ту, в которой наблюдается минимальная корреляция.

print(np.corrcoef(students[:, 1], students[:, 2]))
print(np.corrcoef(students[:, 1], students[:, 3]))
print(np.corrcoef(students[:, 2], students[:, 3]))


[[1.         0.64314431]
 [0.64314431 1.        ]]
[[1.         0.46293714]
 [0.46293714 1.        ]]
[[1.         0.29801325]
 [0.29801325 1.        ]]


In [30]:
#9.5.4
#Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов:

np.std(students[:,3])

0.4517742799230607

In [31]:
#9.5.5
#Посчитайте, чему равна дисперсия значений веса школьников.
#Эту величину можно получить двумя способами: математически, используя определение дисперсии и известную функцию в блоке,
    #или самостоятельно найти подходящую функцию модуля NumPy.
    
np.var(students[:, 2])

60.36

In [32]:
#9.6.4
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

#Массив my_array создан с помощью кода выше. Напишите код, с помощью которого можно извлечь из него центральный
    #фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.
#Код должен содержать имя массива и набор индексов для получения нужного среза. Ответ введите в одну строку без пробелов.

my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [33]:
#9.6.5
#Создайте массив my_sin, состоящий из синусов элементов массива my_array.
#Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после точки-разделителя.

my_sin = np.sin(my_array)
print ("%.3f" % my_sin.sum())

-0.058


In [34]:
#9.6.6
#Создайте массив my_sin, состоящий из синусов элементов массива my_array.
#Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после точки-разделителя.

my_sin = np.sin(my_array)
my_sin[1:4, 1:4] = 1

print ("%.3f" % my_sin.sum())

7.572


In [35]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [36]:
### 9.6.7
#Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов.
#Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя.

a = my_sin[:, 0:4].reshape((10, 2))
print ("%.3f" %  a[:, 0].sum())

2.406


In [37]:
#Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

bigdata = np.array([[x * x for x in range(101, 1000, 2)]])
bigdata

array([[ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
         13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
         17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
         22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
         27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
         32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
         38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
         45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
         52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
         60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
         68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
         76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
         85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
         95481,  96721,  97969,  99225, 100489, 101761, 103041, 

In [38]:
#9.6.8
#Чему равна медиана массива bigdata?

np.median(bigdata)

302501.0

In [39]:
#9.6.9
#Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:

print("%.0f" %  np.std(bigdata))

292095


In [40]:
corr = np.corrcoef(students[:,1], students[:,2]) 

big_secret[0::2, 0::2] = -1

In [41]:
#9.6.10
#Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами?
#Введите полученный ответ без изменений и округлений.

corr = np.corrcoef(bigdata[::, 0::2], bigdata[::, 1::2]) 
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])